### ISSUE TITLE
Design to support for Moving, Streaming, Real Time Data from the onset

### ISSUE THREAD

**Issue by sirinath** [QuantStack/xeus#1]
One area IPython shines is analysis on static data. Computing, charting and visualisation for real time, streaming, changing data is minimal.  This would be an area perhaps that can be improved on. 

Also see: http://www.ankhor.com/, https://github.com/MicrosoftResearch/Dryad, https://github.com/MicrosoftResearch/Naiad

**Comment by JohanMabille** [comment]
That's not relevant to this project.
