### ISSUE TITLE
Please consider using pkg-config for cryptopp

### ISSUE THREAD

**Issue by yurivict** [QuantStack/xeus#113]
https://github.com/QuantStack/xeus/blob/master/CMakeLists.txt#L58

```cppcrypto``` dropped ```cmake``` support. There is ```crypto-cmake``` project that breaks: https://github.com/noloader/cryptopp-cmake/issues/45

If the project doesn't officially support ```cmake```, you probably shouldn't insist on expecting it.

In the FreeBSD port, I have this patch:
```
+FIND_PACKAGE(PkgConfig)
 find_package(nlohmann_json 3.2.0 REQUIRED)
 find_package(xtl 0.5 REQUIRED)
 find_package(cppzmq 4.3.0 REQUIRED)
-find_package(cryptopp REQUIRED)
+pkg_check_modules(cryptopp libcryptopp REQUIRED)
```
that works fine with ```cryptocpp``` project as it is distributed.

**Comment by SylvainCorlay** [comment]
Yeah, we dropped cmake for zeromq because is was not the standard way of building zeromq.

What I think we should do is support both in the same way cppzmq[ supports both cmake and pkg-config for zeromq](https://github.com/zeromq/cppzmq/blob/d641d1de4c8aa7f2dc674d80b3a71469364b9534/CMakeLists.txt#L9-L16).

**Comment by SylvainCorlay** [comment]
So can find what we did for zeromq here:

https://github.com/QuantStack/xeus/blob/master/CMakeLists.txt#L60-L67

**Comment by noloader** [comment]
My apologies for jumping in on other's bugs... If you guys need immediate help them ping me at *noloader*, gmail account. Projects and distros get special privileges.

You are still welcomed to file bug reports if you like. I use them for change control and documentation so if you don't them I may file one on your behalf.
