### ISSUE TITLE
Overriding CMAKE_CXX_FLAGS_DEBUG may cause link error in MSVC

### ISSUE THREAD

**Issue by myd7349** [QuantStack/xeus#123]
When I was trying to create a `xeus` port (https://github.com/Microsoft/vcpkg/pull/5351) for `vcpkg`, I encountered a link error caused by the overriding of `CMAKE_CXX_FLAGS_DEBUG`.

### How to reproduce?

1. Install `vcpkg` on Win10, and install all packages needed by `xeus` via `vcpkg`:

   >vcpkg install cppzmq cryptopp

2. Clone `xeus` and try to build it with `vcpkg`'s cmake toolchain:

    ```bash
    cd xeus
    mkdir build
    cd build
    cmake .. -DCMAKE_TOOLCHAIN_FILE=E:/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x86-windows -DCMAKE_GENERATOR_PLATFORM=Win32 -DXEUS_USE_SHARED_CRYPTOPP=OFF -DCMAKE_BUILD_TYPE=Debug
   ```

3. Open the VS solution generated in previous step and build the `xeus` project (Win32 Debug):

   ```plain-text
    1>cryptopp-static.lib(cryptlib.cpp.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in xauthentication.obj
    1>cryptopp-static.lib(cryptlib.cpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MD_DynamicRelease' in xauthentication.obj
    1>cryptopp-static.lib(misc.cpp.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in xauthentication.obj
    1>cryptopp-static.lib(misc.cpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MD_DynamicRelease' in xauthentication.obj
   ......
   ```

If I change the `Runtime Library` from `Multi-threaded DLL (/MD)` to `Multi-threaded Debug DLL (/MDd)`(that is not overriding the default `CMAKE_CXX_FLAGS_DEBUG`) in the `xeus` project Properties dialog, this link error will disapper.

**Comment by SylvainCorlay** [comment]
Hey @myd7349, thanks for working on the xeus vcpkg package!

Indeed we are never building xeus in debug mode in our CI. I will look into this.

**Comment by myd7349** [comment]
@SylvainCorlay Thanks for your fast reply!

The command line option `-DCMAKE_BUILD_TYPE=Debug` is important to reproduce this issue. Otherwise, `CMAKE_BUILD_TYPE` contains an empty value and the `CMAKE_CXX_FLAGS_DEBUG` overriding will be skipped.

Another question, is there any plan to give an option to build `xeus` as a static library? The reason is explained here: https://github.com/Microsoft/vcpkg/pull/5351#issuecomment-462283971

Thanks again! 

:-)

**Comment by SylvainCorlay** [comment]
I think that the reason for this is that in

https://github.com/QuantStack/xeus/blob/0.18.1/CMakeLists.txt#L198-L201

we actually override the default behavior so that even for a DEBUG build of xeus, we link with the release builds of the dependencies.

**Comment by SylvainCorlay** [comment]
Completely removing these lines should fix the issue.

Just had a quick chat with @JohanMabille about this. (He used it to debug on windows without having to build dependencies in debug mode).

We both think this should remove this completely.

**Comment by SylvainCorlay** [comment]
Could you check that removing it fixes your issue? We would be glad to accept such a PR if it does.

**Comment by myd7349** [comment]
@SylvainCorlay Thanks.

Yeah. I fixed this issue in a similar way before (https://github.com/Microsoft/vcpkg/pull/5351/files#diff-1ea5275a34978a592706e189515f71a1), and it worked for me.

**Comment by myd7349** [comment]
It seems that `cryptopp` package installed via `conda` only contains a `Release` version of `cryptopp-static.lib`. So this line

```cmake
message(STATUS "Forcing tests build type to Release")
set(CMAKE_BUILD_TYPE Release CACHE STRING "Choose the type of build." FORCE)
```

in [```test\CMakeLists.txt```](https://github.com/QuantStack/xeus/blob/master/test/CMakeLists.txt#L24)  is important. Otherwise, the CI will fail.
