### ISSUE TITLE
Option for using xeus as static library

### ISSUE THREAD

**Issue by myd7349** [QuantStack/xeus#124]
Hi!

Is there any plan to give an option to build `xeus` as a static library? The reason is explained here: [Microsoft/vcpkg#5351 (comment)](https://github.com/Microsoft/vcpkg/pull/5351#issuecomment-462283971)

Thanks! Good night. :-)

**Comment by SylvainCorlay** [comment]
This is not a supported scenario at the moment, but I don't see any major blocker why we should not allow it. Marked the issue as a feature request.
