### ISSUE TITLE
could not deserialize message: Signatures don't match

### ISSUE THREAD

**Issue by jtpio** [QuantStack/xeus#172]
Getting the following message from the logs while using `xeus-python`:

```
ERROR: could not deserialize message
Signatures don't match
```

Which seems to be coming from: https://github.com/QuantStack/xeus/blob/b9b474577362d95e43c83556fa9d6c05b8c3c1fe/src/xkernel_core.cpp#L203-L204

Observing this when running a client side test suite that sends many messages on different channels (`control` and `shell`)

I suppose it's referring to the [HMAC signature](https://jupyter-client.readthedocs.io/en/stable/messaging.html#the-wire-protocol)?

**Comment by JohanMabille** [comment]
Yes, the issue is that `xauthentication` verification method is not thread safe.

**Comment by jtpio** [comment]
Trying to reproduce this behavior with tests running on Azure Pipelines here: https://github.com/jtpio/debugger/pull/3

Was hoping to get a log for a test run on CI with this particular message, but that doesn't seem to be as easy to reproduce as when running locally :)

So very likely to be a race condition. Thanks for the fix!

**Comment by pdimens** [comment]
It's been several years, is this issue truly fixed? I get the signatures matching error every time I execute a notebook via `papermill -k xpython`

**Comment by JohanMabille** [comment]
Yes it should be fixed. Which versions of xeus-python and xeus are you using? If you're using the latest xeus-python (i.e. 0.19), can you try 0.18.3 and see if you have the same issue?
