### ISSUE TITLE
Minimum ZeroMQ version inconsistency

### ISSUE THREAD

**Issue by QuLogic** [QuantStack/xeus#183]
The [README.md](https://github.com/QuantStack/xeus/blob/master/README.md#building-from-source) says minimum version is 4.2.5, but the [CMakeLists.txt](https://github.com/QuantStack/xeus/blob/master/CMakeLists.txt#L52) says 4.2.3.

**Comment by SylvainCorlay** [comment]
Thanks. I think the proper value is 4.2.5.
