### ISSUE TITLE
Don't install Jupyter kernel specs during test build

### ISSUE THREAD

**Issue by QuLogic** [QuantStack/xeus#186]
This is not particularly nice (especially with `--sys-prefix`), and doesn't work on builders. At the very least, this is something to be done at install, not build (but I understand it's a bit difficult as it's for tests.)

Jupyter supports something like [`JUPYTER_PATH`](https://jupyter.readthedocs.io/en/latest/projects/jupyter-directories.html#data-files) which could be used to add a kernel spec without installing it system-wide.

**Comment by SylvainCorlay** [comment]
Hey @QuLogic thanks for the report.

I am not sure I understand in which situation we install a kernelspec that should not be installed?

**Comment by QuLogic** [comment]
A kernelspec is installed [here](https://github.com/QuantStack/xeus/blob/master/test/CMakeLists.txt#L183) when building (not even installing) tests. They're only needed for tests though, so shouldn't be installed.

**Comment by QuLogic** [comment]
Fixed by #187. It was squashed and lost all the commit messages, so didn't auto-close this issue.
