### ISSUE TITLE
interrupt_[request/reply] implementation

### ISSUE THREAD

**Issue by SylvainCorlay** [QuantStack/xeus#56]
We are currently lacking the `interupt_[request/reply]` message handling on the control channel.

As mentionned by @spennihana, we should probably change the `xserver` so that the shell socket is polled by a separate thread, and the control socket remains the only polled by the main thread.

The main issue with this design is that the `kernel_shutdown` message, as per [the documentation](http://jupyter-client.readthedocs.io/en/stable/messaging.html#kernel-shutdown) can  be ***sent on either the control or shell channels***.

Ideally we would need to be 100% sure that the kernel shutdown message would only be received on the control socket.

cc @minrk

**Comment by SylvainCorlay** [comment]
<img width="762" alt="screen shot 2018-06-28 at 2 53 57 am" src="https://user-images.githubusercontent.com/2397974/42050080-415c8d58-7b08-11e8-99fb-9a9dfbd72191.png">

**Comment by SylvainCorlay** [comment]
Note: we should probably also do something about the optional `interrupt_mode` field in the kernelspec that was added in version 5.3 of the kernel protocol.

**Comment by SylvainCorlay** [comment]
also linking to discussion with @rgbk and @jasongrout in jupyter-client.

https://github.com/jupyter/jupyter_client/pull/388

**Comment by rgbk** [comment]
Wrong handle!

**Comment by JohanMabille** [comment]
@rgbk what do you mean? Did you delete my answer?

**Comment by SylvainCorlay** [comment]
> what do you mean? Did you delete my answer?

he meant that I should have pinged @rgbkrk

**Comment by rgbk** [comment]
I’m not part of this group.

**Comment by SylvainCorlay** [comment]
cc @JohanMabille you may want to have another look at this one.

**Comment by JohanMabille** [comment]
> Note: we should probably also do something about the optional interrupt_mode field in the kernelspec that was added in version 5.3 of the kernel protocol.

I think this field is for the client, not the kernel, so we don't have anything to do about it.

**Comment by rgbk** [comment]
Why am I on this thread? Please remove me thanks.
