### ISSUE TITLE
Dependency build instructions: Cryptopp

### ISSUE THREAD

**Issue by bkmgit** [QuantStack/xeus#57]
Cryptopp uses makefile. Should a link to https://github.com/noloader/cryptopp-cmake also be added to the readme?

**Comment by bkmgit** [comment]
Ok, cmakelists file is available in release 5.6.5 of Cryptopp, though may want to update to latest release versions which no longer have a cmake lists file by default: https://www.cryptopp.com/wiki/CMake

**Comment by SylvainCorlay** [comment]
Indeed the support dor cmake in ceyptopp was recently dropped. Last time I checked there had not been a release since though.
