### ISSUE TITLE
Problems compiling from source due to nlohmann_json linking

### ISSUE THREAD

**Issue by sdwfrost** [QuantStack/xeus#82]
When compiling xeus from source on Ubuntu 18.04, I get the following error:

```
Linking CXX shared library libxeus.so
/usr/bin/x86_64-linux-gnu-ld: cannot find -lnlohmann_json
collect2: error: ld returned 1 exit status
CMakeFiles/xeus.dir/build.make:435: recipe for target 'libxeus.so.1.0.1' failed
make[2]: *** [libxeus.so.1.0.1] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/xeusget.dir/all' failed
make[1]: *** [CMakeFiles/xeus.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

However, nlohmann_json is a header-only library. If I've install nlohmann_json from source, how do I get xeus to locate it?

**Comment by SylvainCorlay** [comment]
In modern cmake, `target_link_libraries` is also used for header-only libraries. If it cannot find it, it will assume that you are trying to link with a runtime called nlohmann_json whichbis whatbis happening here.

nlohmann_json and other dependencies should be installed with cmake in the same prefix (-D CMAKE_INSTALL_PREFIX).

Is this how you installed nlohmann_json?

**Comment by sdwfrost** [comment]
I install nlohmann_json as follows, without specifying a prefix, as I did with the other dependencies:

```sh
git clone https://github.com/nlohmann/json && \
    cd json && \
    cmake . && \
    make && \
    make install
```

This installs into /usr/local:

```sh
-- Installing: /usr/local/include/nlohmann
-- Installing: /usr/local/include/nlohmann/json.hpp
-- Installing: /usr/local/lib/cmake/nlohmann_json/nlohmann_jsonConfig.cmake
-- Installing: /usr/local/lib/cmake/nlohmann_json/nlohmann_jsonConfigVersion.cmake
-- Installing: /usr/local/lib/cmake/nlohmann_json/nlohmann_jsonTargets.cmake
```

**Comment by SylvainCorlay** [comment]
Ok, then /usr/local is your prefix!
(This should work with master, but we generally recommend to not use the tip of master for any software, but at least the latest released tag).

When building xeus, could you do

`cmake -D CMAKE_INSTALL_PREFIX=/usr/local` and report the outcome?

**Comment by sdwfrost** [comment]
I get the same:

```sh
/usr/bin/x86_64-linux-gnu-ld: cannot find -lnlohmann_json
collect2: error: ld returned 1 exit status
CMakeFiles/xeus.dir/build.make:435: recipe for target 'libxeus.so.1.0.1' failed
make[2]: *** [libxeus.so.1.0.1] Error 1
make[1]: *** [CMakeFiles/xeus.dir/all] Error 2
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/xeus.dir/all' failed
Makefile:129: recipe for target 'all' failed
```

You can see the full list within a Dockerfile I'm working on:

[https://github.com/sdwfrost/polyglot-playground/blob/master/Dockerfile](https://github.com/sdwfrost/polyglot-playground/blob/master/Dockerfile)

**Comment by SylvainCorlay** [comment]
@sdwfrost I figured it out. The latest release of `nlohmann_json` made a backward incompatible change by adding a namespace to its cmake target names.

Cf. issue https://github.com/nlohmann/json/issues/1243 and commit https://github.com/nlohmann/json/commit/33a2154f8dbff1382d84d6e463e31a5ac9f3da18.

I am updating xeus to use the latest `nlohmann_json` and these target names.
