### ISSUE TITLE
Installation without Conda

### ISSUE THREAD

**Issue by egslava** [QuantStack/xeus#99]
Hello!
I'm sorry, I have never used Conda, since I just use pip to manage my software dependencies and environments. So, I'm afraid that installing Conda, when I already have several versions of Python, can cause problems. Is it possible to install Xeus w/o Conda?

For instance, I have already installed Cling and Cling Jupyter Kernel just via pip. But, unfortunately, it doesn't support cell magic :-/

My system is Ubuntu 16.04.

**Comment by martinRenou** [comment]
Hi @egslava, you can install all the dependencies without conda, directly from source. All the steps are explained here https://github.com/QuantStack/xeus#installing-the-dependencies-from-source. And then you can install xeus from source too

**Comment by SylvainCorlay** [comment]
PyPi is not a general-purpose package manager and can only host python packages. If you installed a "cling" package through pip, it probably is not the C++ interpreter!

**Comment by SylvainCorlay** [comment]
closing! feel free to ask should you have other questions.
